version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: 570833929593.dkr.ecr.us-east-2.amazonaws.com/day-in-review_server:latest
    container_name: day-in-review_node-server
    command: npm start
    ports:
      - "5000:5000"
    env_file: ./server/prod.env
    environment:
      - NODE_ENV=production
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: 570833929593.dkr.ecr.us-east-2.amazonaws.com/day-in-review_client:latest
    container_name: day-in-review_react-client
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
